#!/usr/bin/env python3
"""
generate_rank_overrides.py — Copy vanilla EU5 files and replace location rank
identity checks with modifier-based tier checks.

Our 15 custom ranks each set sul_rank_tier in their rank_modifier:
  rural variants = 1, town variants = 2, city variants = 3

Replacements (all single-line):
  location_rank = location_rank:city              → modifier:sul_rank_tier = 3
  location_rank = location_rank:town              → modifier:sul_rank_tier = 2
  location_rank = location_rank:rural_settlement  → modifier:sul_rank_tier = 1
  NOT = { location_rank = location_rank:city }    → NOT = { modifier:sul_rank_tier = 3 }
  is_city = yes                                   → modifier:sul_rank_tier >= 2
  is_city = no                                    → NOT = { modifier:sul_rank_tier >= 2 }
  change_location_rank = location_rank:X          → flagged for manual review

Scope-chained checks (e.g. capital.location_rank) are expanded to scoped blocks.

Usage:
    python tools/generate_rank_overrides.py                # Generate overrides
    python tools/generate_rank_overrides.py --report-only  # Dry run
    python tools/generate_rank_overrides.py --clean        # Remove generated files
"""

import argparse
import os
import re
import sys
from pathlib import Path

# ============================================================================
# Configuration — edit these when adding specializations or changing tiers
# ============================================================================

TIER_VALUES = {
    'rural_settlement': 1,
    'town': 2,
    'city': 3,
}

DEFAULT_VANILLA = Path('/mnt/d/Program Files (x86)/Steam/steamapps/common/Europa Universalis V/game')
HEADER = '# AUTO-GENERATED by generate_rank_overrides.py — do not hand-edit\n'
SKIP_DIRS = {'location_ranks'}
# Files maintained by hand (rank replacements baked in alongside custom changes)
SKIP_FILES = {
    'in_game/common/diseases/bubonic_plague.txt',
    'in_game/common/diseases/great_pestilence.txt',
    'in_game/common/diseases/measles.txt',
    'in_game/common/diseases/smallpox.txt',
}

TIER_MODIFIERS = {
    1: 'modifier:sul_is_rural_settlement_rank_tier',
    2: 'modifier:sul_is_town_rank_tier',
    3: 'modifier:sul_is_city_rank_tier',
}

# Routing effects that replace change_location_rank = location_rank:X
RANK_ROUTING = {
    'rural_settlement': 'sul_set_rank_rural',
    'town': 'sul_set_rank_town',
    'city': 'sul_set_rank_city',
}


# ============================================================================
# Patterns
# ============================================================================

VANILLA_RANK_ALT = '|'.join(TIER_VALUES.keys())

# change_location_rank = location_rank:X (flag only)
RE_CHANGE_RANK = re.compile(
    rf'^(?P<pre>[^#]*?)change_location_rank\s*=\s*(?:location_rank:)?(?P<rank>{VANILLA_RANK_ALT})(?P<post>.*)$'
)

# NOT = { location_rank [?]= location_rank:X } (single-line)
RE_NOT_RANK = re.compile(
    rf'^(?P<indent>\s*)(?P<outer>.*?)'
    rf'NOT\s*=\s*\{{\s*'
    rf'(?P<lhs>[\w.$]*?location_rank[\w.$]*?)\s*(?P<op>\??=)\s*'
    rf'location_rank:(?P<rank>{VANILLA_RANK_ALT})'
    rf'\s*\}}'
    rf'(?P<post>.*)$'
)

# location_rank != location_rank:X (inequality)
RE_RANK_NEQ = re.compile(
    rf'^(?P<indent>\s*)(?P<pre>.*?)'
    rf'(?P<lhs>[\w.$]*?location_rank[\w.$]*?)\s*!=\s*'
    rf'location_rank:(?P<rank>{VANILLA_RANK_ALT})'
    rf'(?P<post>.*)$'
)

# num_location_rank:X (country-scope count trigger)
RE_NUM_RANK = re.compile(
    rf'^(?P<indent>\s*)(?P<pre>.*?)'
    rf'num_location_rank:(?P<rank>{VANILLA_RANK_ALT})'
    rf'\s*(?P<op>[><=!]+)\s*(?P<val>\d+)'
    rf'(?P<post>.*)$'
)

# is_city = yes|no
RE_IS_CITY = re.compile(
    rf'^(?P<indent>\s*)(?P<pre>.*?)'
    rf'is_city\s*=\s*(?P<val>yes|no)'
    rf'(?P<post>.*)$'
)

# is_city block definition (trigger_localization — skip)
RE_IS_CITY_DEF = re.compile(r'^\s*is_city\s*=\s*\{')

# location_rank [?]= location_rank:X (standard check)
RE_RANK_CHECK = re.compile(
    rf'^(?P<indent>\s*)(?P<pre>.*?)'
    rf'(?P<lhs>[\w.$]*?location_rank[\w.$]*?)\s*(?P<op>\??=)\s*'
    rf'location_rank:(?P<rank>{VANILLA_RANK_ALT})'
    rf'(?P<post>.*)$'
)

RE_COMMENT = re.compile(r'^\s*#')


# ============================================================================
# Replacement handlers
# ============================================================================

def _tier(rank):
    return TIER_VALUES[rank]


def replace_change_rank(line, m):
    """Replace change_location_rank = location_rank:X with routing effect."""
    indent = re.match(r'^(\s*)', line).group(1)
    pre = m.group('pre').strip()
    rank = m.group('rank')
    post = m.group('post').rstrip()
    effect = RANK_ROUTING[rank]

    # Handle inline scope: location:X = { change_location_rank = ... }
    if pre:
        new_line = f'{indent}{pre} {effect} = yes{" " + post if post else ""}\n'
    else:
        new_line = f'{indent}{effect} = yes{" " + post if post else ""}\n'
    return new_line, True, None


def replace_not_rank(line, m):
    """NOT = { location_rank = X } → NOT = { modifier:sul_is_X_rank_tier = yes }"""
    indent = m.group('indent')
    outer = m.group('outer').rstrip()
    rank = m.group('rank')
    post = m.group('post').rstrip()
    tier = _tier(rank)

    core = f'NOT = {{ {TIER_MODIFIERS[tier]} = yes }}'
    parts = [indent]
    if outer:
        parts.append(f'{outer} ')
    parts.append(core)
    if post:
        parts.append(f' {post}')
    return ''.join(parts) + '\n', True, None


def replace_is_city(line, m):
    """is_city = yes → NOT rural ; is_city = no → rural"""
    indent = m.group('indent')
    pre = m.group('pre').rstrip()
    val = m.group('val')
    post = m.group('post').rstrip()

    if val == 'yes':
        core = f'NOT = {{ {TIER_MODIFIERS[1]} = yes }}'
    else:
        core = f'{TIER_MODIFIERS[1]} = yes'

    parts = [indent]
    if pre:
        parts.append(f'{pre} ')
    parts.append(core)
    if post:
        parts.append(f' {post}')
    return ''.join(parts) + '\n', True, None


def replace_rank_neq(line, m):
    """location_rank != location_rank:X → NOT = { modifier:sul_is_X_rank_tier = yes }"""
    indent = m.group('indent')
    pre = m.group('pre').rstrip()
    lhs = m.group('lhs')
    rank = m.group('rank')
    post = m.group('post').rstrip()
    tier = _tier(rank)
    mod = TIER_MODIFIERS[tier]

    if '.' in lhs and lhs.endswith('location_rank'):
        scope = lhs.rsplit('.', 1)[0]
        core = f'NOT = {{ {scope} = {{ {mod} = yes }} }}'
    else:
        core = f'NOT = {{ {mod} = yes }}'

    parts = [indent]
    if pre:
        parts.append(f'{pre} ')
    parts.append(core)
    if post:
        parts.append(f' {post}')
    return ''.join(parts) + '\n', True, None


def replace_num_rank(line, m):
    """num_location_rank:X op N → sul_count_tier_N op N (script value)"""
    indent = m.group('indent')
    pre = m.group('pre').rstrip()
    rank = m.group('rank')
    op = m.group('op')
    val = m.group('val')
    post = m.group('post').rstrip()
    tier = _tier(rank)

    sv_name = f'sul_count_tier_{tier}'
    parts = [indent]
    if pre:
        parts.append(f'{pre} ')
    parts.append(f'{sv_name} {op} {val}')
    if post:
        parts.append(f' {post}')
    return ''.join(parts) + '\n', True, f'NEEDS_SCRIPT_VALUE:{sv_name}'


def replace_rank_check(line, m):
    """location_rank = location_rank:X → modifier:sul_is_X_rank_tier = yes"""
    indent = m.group('indent')
    pre = m.group('pre').rstrip()
    lhs = m.group('lhs')
    rank = m.group('rank')
    post = m.group('post').rstrip()
    tier = _tier(rank)
    mod = TIER_MODIFIERS[tier]

    # Scope-chained: capital.location_rank → needs scoped block
    if '.' in lhs and lhs.endswith('location_rank'):
        scope = lhs.rsplit('.', 1)[0]
        core = f'{scope} = {{ {mod} = yes }}'
    else:
        core = f'{mod} = yes'

    parts = [indent]
    if pre:
        parts.append(f'{pre} ')
    parts.append(core)
    if post:
        parts.append(f' {post}')
    return ''.join(parts) + '\n', True, None


# Rule table — order matters, first match wins
RULES = [
    (RE_CHANGE_RANK, replace_change_rank),
    (RE_NOT_RANK,    replace_not_rank),
    (RE_RANK_NEQ,    replace_rank_neq),
    (RE_NUM_RANK,    replace_num_rank),
    (RE_IS_CITY_DEF, None),  # skip — is_city block definition
    (RE_IS_CITY,     replace_is_city),
    (RE_RANK_CHECK,  replace_rank_check),
]


# ============================================================================
# Multi-line NOT block handler
# ============================================================================

def _try_multiline_not(lines, i):
    """
    If line i is 'NOT = {' on its own, check if the block contains a single
    rank check. If so, collapse to single-line NOT = { modifier:... }.
    Returns (replacement_line, next_index) or None.
    """
    not_match = re.match(r'^(\s*)NOT\s*=\s*\{\s*$', lines[i].rstrip())
    if not not_match or RE_COMMENT.match(lines[i]):
        return None

    indent = not_match.group(1)

    # Scan for closing brace
    j = i + 1
    depth = 1
    block_end = None
    while j < len(lines) and depth > 0:
        for ch in lines[j]:
            if ch == '{': depth += 1
            elif ch == '}': depth -= 1
        if depth == 0:
            block_end = j
        j += 1

    if block_end is None:
        return None

    # Extract content lines (skip comments/blank)
    content = []
    for k in range(i + 1, block_end):
        stripped = lines[k].strip()
        if stripped and not stripped.startswith('#'):
            content.append(lines[k])

    if len(content) != 1:
        return None

    # Try rank check
    m = RE_RANK_CHECK.match(content[0])
    if m:
        tier = _tier(m.group('rank'))
        mod = TIER_MODIFIERS[tier]
        lhs = m.group('lhs')
        if '.' in lhs and lhs.endswith('location_rank'):
            scope = lhs.rsplit('.', 1)[0]
            return f'{indent}NOT = {{ {scope} = {{ {mod} = yes }} }}\n', block_end + 1
        return f'{indent}NOT = {{ {mod} = yes }}\n', block_end + 1

    # Try is_city
    m = RE_IS_CITY.match(content[0])
    if m:
        if m.group('val') == 'yes':
            # NOT { is_city = yes } → is rural
            return f'{indent}{TIER_MODIFIERS[1]} = yes\n', block_end + 1
        else:
            # NOT { is_city = no } → NOT rural (= is town or city)
            return f'{indent}NOT = {{ {TIER_MODIFIERS[1]} = yes }}\n', block_end + 1

    return None


# ============================================================================
# File processor
# ============================================================================

SCAN_KEYWORDS = {'location_rank', 'is_city', 'change_location_rank', 'num_location_rank'}


def process_file(content):
    """Process file content. Returns (new_content, change_count, flags)."""
    lines = content.split('\n')
    lines_nl = [l + '\n' for l in lines]
    if lines and lines[-1] == '':
        lines_nl = lines_nl[:-1]

    output = []
    changes = 0
    flags = []
    i = 0

    while i < len(lines_nl):
        line = lines_nl[i]

        if RE_COMMENT.match(line):
            output.append(line)
            i += 1
            continue

        # Try multi-line NOT collapse
        result = _try_multiline_not(lines_nl, i)
        if result:
            replacement, next_i = result
            output.append(replacement)
            changes += 1
            i = next_i
            continue

        # Single-line rules
        matched = False
        for pattern, handler in RULES:
            m = pattern.match(line)
            if m:
                if handler is None:
                    output.append(line)
                else:
                    new_line, changed, flag = handler(line, m)
                    output.append(new_line)
                    if changed:
                        changes += 1
                    if flag:
                        flags.append((i + 1, flag, line.strip()))
                matched = True
                break

        if not matched:
            output.append(line)

        i += 1

    return ''.join(output), changes, flags


# ============================================================================
# Scanner & generator
# ============================================================================

def scan_and_generate(vanilla_root, output_root, report_only=False):
    in_game = vanilla_root / 'in_game'
    if not in_game.is_dir():
        print(f'ERROR: {in_game} not found', file=sys.stderr)
        sys.exit(1)

    written = []
    all_flags = []

    for root, dirs, files in os.walk(str(in_game)):
        root_path = Path(root)
        rel_root = root_path.relative_to(vanilla_root)
        dirs[:] = [d for d in sorted(dirs) if d not in SKIP_DIRS]

        for fname in sorted(files):
            if not fname.endswith('.txt'):
                continue
            fpath = root_path / fname
            try:
                raw = fpath.read_bytes()
                has_bom = raw[:3] == b'\xef\xbb\xbf'
                content = raw.decode('utf-8-sig')
            except (OSError, UnicodeDecodeError):
                continue

            if not any(kw in content for kw in SCAN_KEYWORDS):
                continue

            rel_path = str(rel_root / fname)
            if rel_path.replace('\\', '/') in SKIP_FILES:
                continue
            new_content, changes, flags = process_file(content)

            for line_no, msg, text in flags:
                all_flags.append((rel_path, line_no, msg, text))

            if changes > 0:
                print(f'  {rel_path}: {changes} replacements')
                if not report_only:
                    out_path = output_root / rel_path
                    out_path.parent.mkdir(parents=True, exist_ok=True)
                    enc = 'utf-8-sig' if has_bom else 'utf-8'
                    with open(str(out_path), 'w', encoding=enc) as f:
                        f.write(HEADER)
                        f.write(new_content)
                    written.append(rel_path)
            elif flags:
                print(f'  {rel_path}: {len(flags)} flags')

    return written, all_flags


# ============================================================================
# Report & clean
# ============================================================================

def write_report(path, written, flags):
    with open(str(path), 'w', encoding='utf-8') as f:
        f.write(f'Rank Override Report\n{"="*60}\n\n')
        f.write(f'Files generated: {len(written)}\n')
        f.write(f'Flagged (manual): {len(flags)}\n\n')
        f.write('Generated files:\n')
        for p in sorted(written):
            f.write(f'  {p}\n')
        if flags:
            f.write(f'\nManual review:\n')
            for rp, ln, msg, text in sorted(flags):
                f.write(f'  {rp}:{ln}  [{msg}]\n    {text[:150]}\n')
    print(f'Report: {path}')


def clean_generated(root):
    count = 0
    for dirpath, dirs, files in os.walk(str(root)):
        for fname in files:
            fp = Path(dirpath) / fname
            try:
                with open(str(fp), 'r', encoding='utf-8-sig') as f:
                    if f.readline().strip() == HEADER.strip():
                        fp.unlink()
                        count += 1
            except (OSError, UnicodeDecodeError):
                pass
    print(f'Removed {count} generated files')


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description='Generate vanilla rank override files')
    parser.add_argument('--vanilla', type=Path, default=DEFAULT_VANILLA)
    parser.add_argument('--output', type=Path, default=None)
    parser.add_argument('--report-only', action='store_true')
    parser.add_argument('--clean', action='store_true')
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    mod_root = script_dir.parent
    output_root = args.output or mod_root
    vanilla = args.vanilla

    if not vanilla.is_dir():
        print(f'ERROR: Vanilla not found: {vanilla}', file=sys.stderr)
        sys.exit(1)

    if args.clean:
        clean_generated(output_root)
        return

    print(f'Scanning {vanilla / "in_game"} ...\n')
    written, flags = scan_and_generate(vanilla, output_root, args.report_only)

    print(f'\nFiles: {len(written)}  Flagged: {len(flags)}')

    if flags:
        print(f'\nFLAGGED:')
        for rp, ln, msg, text in sorted(flags):
            print(f'  {rp}:{ln}  [{msg}]')

    write_report(script_dir / 'rank_override_report.txt', written, flags)

    if args.report_only:
        print('(dry run — no files written)')
    else:
        print(f'Wrote {len(written)} files')


if __name__ == '__main__':
    main()
