#!/usr/bin/env python3
"""Generate hardcoded respec tooltip effects from scripted trigger building lists.

Reads sul_is_{spec}_building triggers from sul_triggers.txt, extracts the building
type lists, and generates per-spec tooltip effects that check has_building for each
type and emit a custom_tooltip line.

Usage:
    python tools/generate_respec_tooltips.py

Output:
    in_game/common/scripted_effects/sul_respec_tooltip_generated.txt
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRIGGERS_FILE = ROOT / "in_game" / "common" / "scripted_triggers" / "sul_triggers.txt"
OUTPUT_FILE = ROOT / "in_game" / "common" / "scripted_effects" / "sul_respec_tooltip_generated.txt"

SPECS = ["mining", "farming", "gathering", "woodland", "commercial"]


def parse_building_list(text: str, spec: str) -> list[str]:
    """Extract building_type keys from sul_is_{spec}_building trigger."""
    pattern = rf"sul_is_{spec}_building\s*=\s*\{{(.*?)\n\}}"
    match = re.search(pattern, text, re.DOTALL)
    if not match:
        raise ValueError(f"Could not find sul_is_{spec}_building trigger")

    body = match.group(1)
    buildings = re.findall(r"building_type\s*=\s*building_type:(\S+)", body)
    # Filter out respec carrier buildings
    buildings = [b for b in buildings if not b.startswith("sul_respec_")]
    return buildings


def generate_tooltip_effect(spec: str, all_buildings: dict[str, list[str]]) -> str:
    """Generate a sul_respec_show_destroy_non_{spec} effect."""
    lines = []
    lines.append(f"sul_respec_show_destroy_non_{spec} = {{")

    # Collect buildings from OTHER specs (not this one)
    target_buildings = set()
    for other_spec, bldgs in all_buildings.items():
        if other_spec != spec:
            target_buildings.update(bldgs)

    # Sort for determinism
    for building in sorted(target_buildings):
        lines.append(f"\tif = {{")
        lines.append(f"\t\tlimit = {{ has_building = building_type:{building} }}")
        lines.append(f"\t\tcustom_tooltip = SUL_RESPEC_DESTROY_{building}")
        lines.append(f"\t}}")

    lines.append("}")
    return "\n".join(lines)


def generate_loc_keys(all_buildings: dict[str, list[str]]) -> list[str]:
    """Generate loc keys for each building destruction line."""
    all_building_keys = set()
    for bldgs in all_buildings.values():
        all_building_keys.update(bldgs)

    keys = []
    for building in sorted(all_building_keys):
        keys.append(
            f' SUL_RESPEC_DESTROY_{building}: '
            f'"#R [ShowBuildingTypeName(\'{building}\')] will be destroyed.#!"'
        )
    return keys


def main():
    text = TRIGGERS_FILE.read_text(encoding="utf-8-sig")

    all_buildings = {}
    for spec in SPECS:
        all_buildings[spec] = parse_building_list(text, spec)
        print(f"  {spec}: {len(all_buildings[spec])} buildings")

    # Generate effects
    output_lines = [
        "# AUTO-GENERATED by tools/generate_respec_tooltips.py",
        "# Do not hand-edit. Regenerate after changing sul_is_*_building triggers.",
        "",
    ]

    for spec in SPECS:
        output_lines.append(generate_tooltip_effect(spec, all_buildings))
        output_lines.append("")

    OUTPUT_FILE.write_text("\n".join(output_lines), encoding="utf-8-sig")
    print(f"  Written: {OUTPUT_FILE.relative_to(ROOT)}")

    # Generate loc keys
    loc_keys = generate_loc_keys(all_buildings)
    loc_file = ROOT / "main_menu" / "localization" / "english" / "sul_respec_tooltips_l_english.yml"
    loc_lines = ["l_english:"] + loc_keys
    loc_file.write_text("\n".join(loc_lines) + "\n", encoding="utf-8-sig")
    print(f"  Written: {loc_file.relative_to(ROOT)} ({len(loc_keys)} keys)")


if __name__ == "__main__":
    main()
